### ISSUE TITLE
Virus Total is showing virus

### ISSUE THREAD

**Issue by Hifilo** [LiveEnhancementSuite/LESforWindows#15]
Hi just noticed this is getting flagged, wanted to let you know.

Cheers.

![image](https://user-images.githubusercontent.com/92943726/142720329-bf92d035-7e45-4aa1-b1fa-ec63c956b14d.png)

**Comment by Inversil** [comment]
This is getting flagged because its built on Autohotkey, not because it's actually malicious. 
All Autohotkey executables get flagged by most of these, regardless of heuristic behavior, and it's been bothersome for people that actually still use these AVs in 2021.

If you don't trust it, feel free to read the source code and compile it yourself; if you use compileahk and include the icons, it will be the exact same.
