### ISSUE TITLE
[Feature] Velocity lock when drawing in piano roll with ` shortcut.

### ISSUE THREAD

**Issue by Aga111555** [LiveEnhancementSuite/LESforWindows#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Inversil** [comment]
Hello!
Thanks for your suggestion

hmmmm yeah I see what you mean
The velocity change by moving vertically on the screen after drawing is part of Live's user interface.

I tried doing this exact thing when I was first creating the shortcut initially a few years ago, but nothing lets me do that short of forcefully preventing the mouse from moving vertically until the click is released. 
I did eventually manage to get that to work, but it felt awkward at best; because this approach also stunted horizontal movement / made the mouse laggy.

If someone is able to do it in a way that feels decent to use, feel free to recreate the issue/request.
