### ISSUE TITLE
Midi menu shows up instead of plugin menu

### ISSUE THREAD

**Issue by LDsound** [LiveEnhancementSuite/LESforWindows#18]
ALES will only show the midi menu, (scales, chords) instead of my custom plugin menu when double right-clicking on my effect rack. This functionally renders the menu useless. It doesn't happen all the time. Sometimes when I open Ableton it's working correctly but it will almost always switch at some point. I didn't think it ever switched back after it had stopped working but it just did, as far as I can remember that has only happened once during a session. When iI leave and reopen Ableton it will sometimes be fixed for a little while but not always. When it is happening the only double right-click menu that shows up is the midi menu. The plugin menu does not show when right-clicking on the midi window so they're not switched. I haven't been able to figure out what triggers it or link it to anything in particular, but it feels like there is something that I must do that confuses ALES into thinking I'm always looking at the midi window.

Running Windows 11 (happened on windows 10 too) and Ableton Live 10 Suite

**Comment by A5Kush** [comment]
I am also in the same situation. The temporary solution for me is to shrink the ableton and open it again.

**Comment by Inversil** [comment]
Hi there!!

The midi menu detection is actually super simple and not entirely foolproof. What it does is it essentially scans the bottom half of your screen for the colours of the piano on the left side I.E. Full black # 000000 and full white # FFFFFF. These are the only colors in live that don't change depending on theme or brightness settings. 

However, because actually requesting the color of every pixel through win32 is incredibly slow, it only checks a few spots at random. 

If it misdetects, it's because there is something on the bottom half of your screen that looks like a piano!
I'm guessing the chains or macro colours in your effect rack are black and/or white? That tripping up the check is unusual, but not impossible. You can even fool it by moving plugin UI's with pianos on them into the bottom left corner in a precise way and it will happen too.
It's a bit finnicky, but it ended up being more intuitive than forcing people to hit shift alongside their double right click.

If you went out of your way to check the documentation you would've already found the solution here: https://docs.enhancementsuite.me/shortcut_menus.html#piano-menu
> The piano menu shows up if the piano roll is detected on screen. If the piano roll detection often fails for you, you can set it to manual mode by editing settings.ini

In this way you can open the midi menu only when you're holding shift while you double right click, so it should never show up when you don't want it to. I think I'll make it the default in the next patch.

I know musicians don't like checking out manuals, but this is a finnicky script tool hacked together by a music kid.
Even though it's gotten pretty rigorous through lots of testing, I still recommend the docs :)

hope that helps! feel free to reopen the issue or just quickly create a new one if it didn't; but I'm pretty sure I got you covered.

**Comment by Inversil** [comment]
reopening this just so I don't forget to change the default setting

**Comment by enoversum** [comment]
…I had this all the time, never needed the MIDI menu, and simply disabled it. So happy afterwards ❤️❤️.

**Comment by Inversil** [comment]
fixed in this commit!
https://github.com/LiveEnhancementSuite/LESforWindows/commit/d4b9f122867e781974545b2a21eb890e6c495ed3
